name: "🐛 Bug Report (แบบฟอร์ม)"
description: "ใช้แบบฟอร์มนี้เพื่อแจ้งปัญหาที่พบในโค้ด"
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["ing1403/12"]
body:
  - type: markdown
    attributes:
      value: |
        ขอบคุณที่ช่วยแจ้งปัญหา! กรุณากรอกรายละเอียดด้านล่างเพื่อให้เราแก้ไขได้รวดเร็วขึ้น

  - type: textarea
    id: what-happened
    attributes:
      label: "เกิดอะไรขึ้น? (What happened?)"
      description: "อธิบายปัญหาที่พบสั้นๆ"
      placeholder: "เช่น ปุ่ม Login กดแล้วไม่ทำงาน..."
    validations:
      required: true # <--- บังคับว่าต้องกรอก ห้ามเว้นว่าง!

  - type: dropdown
    id: platform
    attributes:
      label: "ปัญหาเกิดบนระบบไหน?"
      options:
        - Web Browser
        - Android
        - iOS
        - Desktop
    validations:
      required: true

  - type: textarea
    id: version-info
    attributes:
      label: "ข้อมูลเวอร์ชัน"
      description: "เช่น Chrome เวอร์ชัน 120 หรือ Node.js v20"
      placeholder: "ใส่ข้อมูลที่นี่..."

  - type: checkboxes
    id: checks
    attributes:
      label: "การตรวจสอบเบื้องต้น"
      options:
        - label: "ฉันได้ลองรีสตาร์ทเครื่องแล้ว"
          required: true
        - label: "ฉันมั่นใจว่าไม่ใช่ความผิดพลาดของอินเทอร์เน็ต"
          required: false

  - type: markdown
    attributes:
      value: "---"